server:
  port: 8087
spring:
  application:
    name: bidding-application
  datasource:
    url: jdbc:mysql://localhost:3306/password
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: "org.hibernate.dialect.MySQLDialect"